filebeat.inputs:
  - type: log
    paths:
      - /var/app/log/*.log
    json.keys_under_root: true
    json.add_error_key: true
    json.overwrite_keys: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
